server:
  port: 8081
jwt:
  token:
    secretKey: planete-chef
chefplanete:
  isUsingMocks: true
oauth2:
  resource:
    clientIds: 269141253852-k5l3rnk3r9guv45i4ovsi8haoc91qpmp.apps.googleusercontent.com, 269141253852-sfvud8v5grcbku07bu7ncqrt55k56gss.apps.googleusercontent.com, 269141253852-b4c1k1n4100dd87hjmehva5l7r81u06n.apps.googleusercontent.com
spring:
  cloud:
    gcp:
      credentials:
        location: classpath:ChefPlanete-28639703da8b.json
  data:
    mongodb:
      host: localhost
      port: 27017
      username: chef
      password: password
      database: chefplanete